version: '3.9'


services:

  postgresDB:
      container_name: postgresDB
      image: postgres:latest
      restart: always
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=19203856
        - POSTGRES_DB=task5

  kafka:
    container_name: 'kafka'
    hostname: 'kafka'
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  zookeeper:
    container_name: 'zookeeper'
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  common:
    container_name: 'common'
    build: common/
    ports:
      - 8080:8080
    depends_on:
      - kafka
      - postgresDB

  admin:
    container_name: 'admin'
    build: admin/
    ports:
      - 8081:8081
    depends_on:
      - kafka
      - postgresDB