version: '3.9'

volumes:
  postgres-data:

services:
  task5:
      container_name: task5
      image: postgres:latest
      restart: always
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=19203856
        - POSTGRES_DB=task5
      volumes:
        - postgres-data:/var/lib/postgresql/data